version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    image: nononoletmecontainerize/group3:frontend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    image: nononoletmecontainerize/group3:backend
    environment:
      - CHOKIDAR_USEPOLLING=true
