name: Deploy to Staging Server

on:
  push:
    branches:
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml build
    - name: Publish the docker image
      run: docker compose -f docker-compose.yml push
           
  
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy docker container webhook
        run: curl -X POST ${{ secrets.DEPLOY_WEBHOOK_URL }}
